management.endpoints.web.exposure.include: '*'

spring:
  datasource:
    url: jdbc:postgresql://${spring.datasource.ext.host}:5432/${spring.datasource.ext.database-name}
    username: postgres
    password: '{cipher}37b051e4b5154a4371dd20d85b8d0b30f5eb429f6ca7415479dc407289c67547'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect